version: '3.3'

services:
  web:
    build: .
    # image: ghcr.io/democraciaenred/demoreset-web:0.6.0
    image: demoreset-web:latest
    environment:
      API_URL: https://content.demoreset.democraciaenred.org
      EXPRESS_API: http://localhost:4000/api
    ports:
      - 3000:3000